"""Init models

Revision ID: 5f518c0abc8c
Revises: 
Create Date: 2024-09-27 22:07:58.347100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f518c0abc8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('cover', sa.LargeBinary(), nullable=True),
                    sa.Column('datetime', sa.DateTime(), nullable=False),
                    sa.Column('token_model', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('ip_address', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('clip',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer()),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('about', sa.String(), nullable=True),
                    sa.Column('duration', sa.Integer(), nullable=False),
                    sa.Column('cover', sa.LargeBinary(), nullable=True),
                    sa.Column('tags', sa.String(), nullable=True),
                    sa.Column('subtitles', sa.String, nullable=True),
                    sa.Column('start', sa.Integer(), nullable=True),
                    sa.Column('end', sa.Integer(), nullable=True),
                    sa.Column('subtitle', sa.Boolean(), nullable=False),
                    sa.Column('adhd', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_project',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('project_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_project')
    op.drop_table('clip')
    op.drop_table('user')
    op.drop_table('project')
    # ### end Alembic commands ###
