version: '3'
services:
    react:
        container_name: react_web
        build:
            context: ./
            dockerfile: Dockerfile_react
        ports:
            - "3000:3000"
        volumes:
            - ./public/:/opt/react/public
            - ./src/:/opt/react/src
            - ./package-lock.json/:/opt/react/package-lock.json
            - ./package.json/:/opt/react/package.json
        depends_on:
            - app

    app:
        container_name: app_web
        build:
            context: ./
            dockerfile: Dockerfile_app
        command: python main.py
        volumes:
            - ./storage/:/opt/web/storage
            - ./db_tools/:/opt/web/db_tools
            - ./alembic/:/opt/web/alembic
            - ./main.py/:/opt/web/main.py
            - ./model.py/:/opt/web/model.py
            - ./video_tools.py/:/opt/web/video_tools.py
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db
    db:
        container_name: db_web
        image: postgres:15
        ports:
            - "5432:5432"
        volumes:
            - ./postgres_data/:/var/lib/postgresql/data
        env_file:
            - .env
