FROM python:3.11

WORKDIR /opt/web/

COPY . /opt/web/

ENV DOCKER_CONTAINER=1

RUN apt-get update && apt-get install -y libgl1-mesa-glx libglu1-mesa libglib2.0-0

COPY requirements.txt ./

RUN  pip install --upgrade pip \
    && pip install -r requirements.txt

CMD ["python", "main.py"]